company = "Rothenberger"
pathtype = "network"
veeam = "yes"
sql = "yes"
sextension = ".zip"
vpath = "\\\\192.168.48.19\\Servers Backup\\"
vpath2 = "\\\\192.168.48.248\\VEEAM_BnR_BACKUP\\"
spath = "\\\\192.168.48.211\\MsSqlBackup\\"
