company = "Słodkie Upominki"
pathtype = "network"
veeam = "yes"
sql = "yes"
vpath = "\\\\192.168.1.252\\altaro\\"
vpath2 = "\\\\192.168.1.251\\Backup\\"
spath = "\\\\192.168.1.252\\backup_wapro\\Dzienny\\"
